// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uawbrrkphwwwnrsyfxdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhd2JycmtwaHd3d25yc3lmeGRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODM2NzksImV4cCI6MjA2ODg1OTY3OX0.Vsk6Qa7IluxxCina-od-YnsqnssamVtzZzVSRGej9j4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'atmos-africa-connect/1.0.0'
    }
  }
});